# Generated by Django 5.2.3 on 2025-09-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
