# Generated by Django 5.2.3 on 2025-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0002_customfields_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='check_constraint',
            field=models.CharField(blank=True, help_text="Raw SQL for CHECK, e.g. 'age > 0'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customfields',
            name='default_value',
            field=models.CharField(blank=True, help_text='Literal default value for SQL DEFAULT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customfields',
            name='is_not_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfields',
            name='is_primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfields',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
