# Generated by Django 5.2.3 on 2025-09-29 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0003_customfields_check_constraint_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, related_name='group_tables', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customtable',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
