# Generated by Django 5.2.3 on 2025-10-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0004_customtable_visible_to_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskNameDisplay', models.CharField(max_length=100)),
                ('TaskName', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedBy', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTaskFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('TaskTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskFields', to='FileMngmntApp.customtasktable')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTaskRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_row_id', models.IntegerField()),
                ('assigned_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_from', to='FileMngmntApp.customtable')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskRows', to='FileMngmntApp.customtasktable')),
            ],
        ),
    ]
