# Generated by Django 5.2.3 on 2025-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0005_customtasktable_customtaskfields_assignedtaskrows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtasktable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
