# Generated by Django 5.2.3 on 2025-11-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0006_customtasktable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtasktable',
            name='BaseTable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseTable', to='FileMngmntApp.customtable'),
        ),
    ]
