# Generated by Django 5.2.6 on 2025-11-29 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0007_customtasktable_basetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtasktable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customtasktable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
