# Generated by Django 5.2.6 on 2025-12-09 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0008_alter_customtasktable_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='users_can_edit',
            field=models.ManyToManyField(blank=True, related_name='can_edit_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
