# Generated by Django 5.2.6 on 2026-02-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0009_customtable_users_can_edit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileMngmntApp.customtable')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardGroupColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_columns', to='FileMngmntApp.dashboard')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileMngmntApp.customfields')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
