# Generated by Django 5.2.6 on 2026-02-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0010_dashboard_dashboardgroupcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeUniqueConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(related_name='unique_groups', to='FileMngmntApp.customfields')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_uniques', to='FileMngmntApp.customtable')),
            ],
        ),
    ]
