# Generated by Django 5.2.6 on 2026-02-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0011_compositeuniqueconstraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='field_kind',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=20),
        ),
    ]
