# Generated by Django 5.2.6 on 2026-02-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0012_customfields_field_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfields',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='customfields',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customfields',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='customfields',
            unique_together={('table', 'field_name')},
        ),
        migrations.CreateModel(
            name='TableSchemaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rename', 'Rename Column'), ('constraint', 'Alter Constraint'), ('add_column', 'Add Column'), ('drop_column', 'Drop Column')], max_length=50)),
                ('sql_executed', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_changes', to='FileMngmntApp.customtable')),
            ],
        ),
    ]
