# Generated by Django 5.2.6 on 2026-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0013_alter_customfields_options_customfields_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositeuniqueconstraint',
            name='constraint_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
