# Generated by Django 5.2.6 on 2026-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0014_compositeuniqueconstraint_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='table_type',
            field=models.CharField(choices=[('project', 'Project'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
