# Generated by Django 5.2.6 on 2026-04-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileMngmntApp', '0017_holiday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('project', 'date')},
        ),
    ]
